version: '3.3'

services:
  # Spring Boot application
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_DOCKER_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - spring_network

  # PostgreSQL database
  db:
    image: postgres:14
    container_name: springboot-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: tasks_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - spring_network

volumes:
  db_data:

networks:
  spring_network:
